name: Dashboard Deploy
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: yarn install

        - name: Run tests
          run: yarn test

        - name: Build
          run: yarn build

        - name: Deploy
        - uses: ./.github/actions/s3upload-action
            with:
              keyid: ${{ secrets.AWS_ACCESS_KEY_ID }}
              accesskey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              region: "eu-west-3"
              filepath: "."
              bucket: "s3://oscarmirandadashboard"
              options: "--recursive"